### ISSUE TITLE
Kr8s example?

### ISSUE THREAD

**Issue by cupdike** [run-ai/runai-samples#3]
Has anyone gotten Kr8s to work with Runai CRDs?  I naively took a run at it based on this:
https://docs.kr8s.org/en/latest/object.html#using-custom-objects-with-other-kr8s-functions

But never got anything that could actually retrieve Runai objects:

```
import kr8s as kc
from kr8s.objects import new_class
from pprint import pprint
import os

os.environ["KUBECONFIG"] = "mykubeconfig.yaml"

def get_crd(namepart):
    for crd in kc.objects.CustomResourceDefinition.list():
        if namepart in crd.name:
            return crd

# kc get crd interactiveworkloads.run.ai -o yaml | grep -i apiVersion
# ==> apiVersion: apiextensions.k8s.io/v1
iw_crd = get_crd('interactiveworkloads')
p_crd = get_crd('projects')
print("##### interactiveworkload crd, name:", iw_crd.name, "version:", iw_crd.version)
print("##### project crd, name:", p_crd.name, "version:", p_crd.version)

# This does work as far as matching the class
InteractiveWorkload = new_class(
        kind="interactiveworkload", # always singular
        version="v2alpha1",  
        #group="run.ai",     
        namespaced=True,
        asyncio=True,
    )

Project = new_class(
        kind="project", # always singular
        version="v2alpha1",
        #group="run.ai",        
        namespaced=False,
        asyncio=True,
    )

iw_class = InteractiveWorkload({})
p_class = Project({})

kc.get("interactiveworkloads", base="v2alpha1",namespace="runai_myproject", api=iw_crd.api)
#'500 Internal Server Error' for url 'https://mycluster/k8s/clusters/myclusterid/v1/run.ai/namespaces/runai_myproject/interactiveworkloads'

kc.get("projects", base="v2alpha1", api=iw_crd.api)
#'500 Internal Server Error' for url 'https://mycluster/k8s/clusters/myclusterid/v1/run.ai/projects' 
```

If anyone has gotten this, or another python k8s client working (lightcube, etc), I'd be interested in examples.
TIA

**Comment by jacobtomlinson** [comment]
Hey there! Author or `kr8s` here (sorry can't help check GitHub for mentions of `kr8s` from time to time).

At a glance it looks like you're running into https://github.com/kr8s-org/kr8s/issues/284. Would you be able to use `kubectl proxy` to proxy your Kuberneter cluster's API and then try again with `kr8s`? If it's the same issue that would definitely help prioritise a fix in `kr8s`.

**Comment by cupdike** [comment]
I tried using kubectl proxy several different ways but only seem to get 404 or 301 errors.  What specific proxy command should I be using based on based on `https://mycluster/k8s/clusters/myclusterid/`?

**Comment by jacobtomlinson** [comment]
I would expect you could do something like:

Proxy your run.ai cluster to localhost. This removes all the `mycluster/k8s/clusters/myclusterid/` URL prefix.

```bash
$ kubectl proxy
Starting to serve on 127.0.0.1:8001
```

Tell kr8s to connect to the proxies client.

```python
import kr8s as kc

client = kc.api(url="http://127.0.0.1:8001")  # You don't need to use client again unless you want to as kr8s will look up the pointer to it internally

# Rest of your code goes here
```

**Comment by cupdike** [comment]
That still gets a 301
```
httpx.HTTPStatusError: Redirect response '301 Moved Permanently' for url 'http://127.0.0.1:8001/api/'
Redirect location: '/api'
```

**Comment by jacobtomlinson** [comment]
Can you try the latest release? I just fixed that today.

**Comment by cupdike** [comment]
The latest release DOES work using this proxy (thanks!):
`kubectl proxy  --append-server-path`
WIth this:
```
api = kr8s.api(url="http://127.0.0.1:8001/", namespace=kr8s.ALL)
print(api.get("pods"))
```
However, I'm kind of back at the original problem:
```
Project = new_class(
        kind="project", # always singular
        version="v2alpha1",
        #group="run.ai",        
        namespaced=False,
        asyncio=True,
    )

p_class = Project({})
kr8s.get("projects", base="v2alpha1", api=p_crd.api)

# KeyError: No object registered for projects.
```
I'm not very familiar with CRDs and k8s apis so I'm probably not using the right values for arguments.

**Comment by jacobtomlinson** [comment]
I'm not sure you're setting your `version` correctly and you don't need the `group` that you have commented out. You don't need to specify `asyncio=True` and you're setting `base=` in `kr8s.get` which isn't doing what you think it does and I don't think you should need to mess with `httpx` kwargs like that.

If you run `kubectl api-resources` you will see a list of all the registered resources. You want the version from the `APIVERSION` column, my guess is you want `run.ai/v2alpha1` but you should double check.

So you probably want something like the following:

```python
import kr8s
from kr8s.objects import new_class

# Create the client, you're setting the default namespace to ALL but then querying non-namespaced 
# objects so this might not be necessary.
api = kr8s.api(url="http://127.0.0.1:8001/", namespace=kr8s.ALL)

# Next create a class for the Custom Resource that you want to query
# You should only need to set the name, version and namespaced kwargs
Project = new_class("project", version="run.ai/v2alpha1", namespaced=False)

# Now you should be able to just list projects
kr8s.get("projects")
```

**Comment by cupdike** [comment]
It's working now!  And it works without the running the proxy.  Wasn't aware of `kubectl api-resources` and was getting lost in the CRD descriptions.  Thanks for reaching out and the hand-holding.
